name = "dd-ld-varde-place-live-worker"
main = "worker/src/index.ts"
compatibility_date = "2026-07-26"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["* * * * *"]

[limits]
subrequests = 10000

[vars]
RESEARCH_ARCHIVE_ENABLED = "true"
